/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  AddressLike,
  BaseContract,
  BigNumberish,
  BytesLike,
  ContractMethod,
  ContractRunner,
  EventFragment,
  FunctionFragment,
  Interface,
  Listener,
  Result,
} from "ethers";
import type {
  TypedContractEvent,
  TypedContractMethod,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedLogDescription,
} from "../../common";

export declare namespace WithdrawalLib {
  export type WithdrawalStruct = {
    recipient: AddressLike;
    tokenIndex: BigNumberish;
    amount: BigNumberish;
    nullifier: BytesLike;
  };

  export type WithdrawalStructOutput = [
    recipient: string,
    tokenIndex: bigint,
    amount: bigint,
    nullifier: string
  ] & {
    recipient: string;
    tokenIndex: bigint;
    amount: bigint;
    nullifier: string;
  };
}

export declare namespace DepositLib {
  export type DepositStruct = {
    depositor: AddressLike;
    recipientSaltHash: BytesLike;
    amount: BigNumberish;
    tokenIndex: BigNumberish;
    isEligible: boolean;
  };

  export type DepositStructOutput = [
    depositor: string,
    recipientSaltHash: string,
    amount: bigint,
    tokenIndex: bigint,
    isEligible: boolean
  ] & {
    depositor: string;
    recipientSaltHash: string;
    amount: bigint;
    tokenIndex: bigint;
    isEligible: boolean;
  };
}

export declare namespace DepositQueueLib {
  export type DepositDataStruct = {
    depositHash: BytesLike;
    sender: AddressLike;
  };

  export type DepositDataStructOutput = [
    depositHash: string,
    sender: string
  ] & { depositHash: string; sender: string };
}

export declare namespace ITokenData {
  export type TokenInfoStruct = {
    tokenType: BigNumberish;
    tokenAddress: AddressLike;
    tokenId: BigNumberish;
  };

  export type TokenInfoStructOutput = [
    tokenType: bigint,
    tokenAddress: string,
    tokenId: bigint
  ] & { tokenType: bigint; tokenAddress: string; tokenId: bigint };
}

export interface LiquidityInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "RELAYER"
      | "UPGRADE_INTERFACE_VERSION"
      | "WITHDRAWAL"
      | "WITHDRAWAL_FEE_RATIO_LIMIT"
      | "amlPermitter"
      | "cancelDeposit"
      | "claimWithdrawals"
      | "claimableWithdrawals"
      | "collectedWithdrawalFees"
      | "deploymentTime"
      | "depositERC1155"
      | "depositERC20"
      | "depositERC721"
      | "depositNativeToken"
      | "eligibilityPermitter"
      | "getDepositData"
      | "getDepositDataBatch"
      | "getDepositDataHash"
      | "getLastDepositId"
      | "getLastRelayedDepositId"
      | "getNativeTokenIndex"
      | "getRoleAdmin"
      | "getTokenIndex"
      | "getTokenInfo"
      | "grantRole"
      | "hasRole"
      | "initialize"
      | "isDepositValid"
      | "onERC1155Received"
      | "pauseDeposits"
      | "paused"
      | "processWithdrawals"
      | "proxiableUUID"
      | "relayDeposits"
      | "renounceRole"
      | "revokeRole"
      | "setPermitter"
      | "setWithdrawalFeeRatio"
      | "supportsInterface"
      | "unpauseDeposits"
      | "upgradeToAndCall"
      | "withdrawCollectedFees"
      | "withdrawalFeeRatio"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimedWithdrawal"
      | "DepositCanceled"
      | "Deposited"
      | "DepositsRelayed"
      | "DirectWithdrawalFailed"
      | "DirectWithdrawalSuccessed"
      | "Initialized"
      | "Paused"
      | "PermitterSet"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
      | "Upgraded"
      | "WithdrawalClaimable"
      | "WithdrawalFeeCollected"
      | "WithdrawalFeeRatioSet"
      | "WithdrawalFeeWithdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "RELAYER", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WITHDRAWAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "WITHDRAWAL_FEE_RATIO_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "amlPermitter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelDeposit",
    values: [BigNumberish, DepositLib.DepositStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "claimWithdrawals",
    values: [WithdrawalLib.WithdrawalStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimableWithdrawals",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "collectedWithdrawalFees",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deploymentTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC1155",
    values: [
      AddressLike,
      BytesLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC20",
    values: [AddressLike, BytesLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositERC721",
    values: [AddressLike, BytesLike, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositNativeToken",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "eligibilityPermitter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositDataBatch",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getDepositDataHash",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLastDepositId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLastRelayedDepositId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNativeTokenIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenIndex",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike,
      AddressLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isDepositValid",
    values: [
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish,
      boolean,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "onERC1155Received",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pauseDeposits",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processWithdrawals",
    values: [WithdrawalLib.WithdrawalStruct[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "relayDeposits",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPermitter",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setWithdrawalFeeRatio",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unpauseDeposits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCollectedFees",
    values: [AddressLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawalFeeRatio",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "RELAYER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "WITHDRAWAL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "WITHDRAWAL_FEE_RATIO_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "amlPermitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectedWithdrawalFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deploymentTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositERC721",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositNativeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eligibilityPermitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositDataBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDepositDataHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastDepositId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLastRelayedDepositId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNativeTokenIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isDepositValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC1155Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pauseDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "relayDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPermitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWithdrawalFeeRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unpauseDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCollectedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawalFeeRatio",
    data: BytesLike
  ): Result;
}

export namespace ClaimedWithdrawalEvent {
  export type InputTuple = [recipient: AddressLike, withdrawalHash: BytesLike];
  export type OutputTuple = [recipient: string, withdrawalHash: string];
  export interface OutputObject {
    recipient: string;
    withdrawalHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositCanceledEvent {
  export type InputTuple = [depositId: BigNumberish];
  export type OutputTuple = [depositId: bigint];
  export interface OutputObject {
    depositId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositedEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    sender: AddressLike,
    recipientSaltHash: BytesLike,
    tokenIndex: BigNumberish,
    amount: BigNumberish,
    isEligible: boolean,
    depositedAt: BigNumberish
  ];
  export type OutputTuple = [
    depositId: bigint,
    sender: string,
    recipientSaltHash: string,
    tokenIndex: bigint,
    amount: bigint,
    isEligible: boolean,
    depositedAt: bigint
  ];
  export interface OutputObject {
    depositId: bigint;
    sender: string;
    recipientSaltHash: string;
    tokenIndex: bigint;
    amount: bigint;
    isEligible: boolean;
    depositedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositsRelayedEvent {
  export type InputTuple = [
    upToDepositId: BigNumberish,
    gasLimit: BigNumberish,
    message: BytesLike
  ];
  export type OutputTuple = [
    upToDepositId: bigint,
    gasLimit: bigint,
    message: string
  ];
  export interface OutputObject {
    upToDepositId: bigint;
    gasLimit: bigint;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DirectWithdrawalFailedEvent {
  export type InputTuple = [
    withdrawalHash: BytesLike,
    withdrawal: WithdrawalLib.WithdrawalStruct
  ];
  export type OutputTuple = [
    withdrawalHash: string,
    withdrawal: WithdrawalLib.WithdrawalStructOutput
  ];
  export interface OutputObject {
    withdrawalHash: string;
    withdrawal: WithdrawalLib.WithdrawalStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DirectWithdrawalSuccessedEvent {
  export type InputTuple = [withdrawalHash: BytesLike, recipient: AddressLike];
  export type OutputTuple = [withdrawalHash: string, recipient: string];
  export interface OutputObject {
    withdrawalHash: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PermitterSetEvent {
  export type InputTuple = [
    amlPermitter: AddressLike,
    eligibilityPermitter: AddressLike
  ];
  export type OutputTuple = [
    amlPermitter: string,
    eligibilityPermitter: string
  ];
  export interface OutputObject {
    amlPermitter: string;
    eligibilityPermitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalClaimableEvent {
  export type InputTuple = [withdrawalHash: BytesLike];
  export type OutputTuple = [withdrawalHash: string];
  export interface OutputObject {
    withdrawalHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalFeeCollectedEvent {
  export type InputTuple = [token: BigNumberish, amount: BigNumberish];
  export type OutputTuple = [token: bigint, amount: bigint];
  export interface OutputObject {
    token: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalFeeRatioSetEvent {
  export type InputTuple = [tokenIndex: BigNumberish, feeRatio: BigNumberish];
  export type OutputTuple = [tokenIndex: bigint, feeRatio: bigint];
  export interface OutputObject {
    tokenIndex: bigint;
    feeRatio: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalFeeWithdrawnEvent {
  export type InputTuple = [
    recipient: AddressLike,
    token: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [recipient: string, token: bigint, amount: bigint];
  export interface OutputObject {
    recipient: string;
    token: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Liquidity extends BaseContract {
  connect(runner?: ContractRunner | null): Liquidity;
  waitForDeployment(): Promise<this>;

  interface: LiquidityInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  RELAYER: TypedContractMethod<[], [string], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  WITHDRAWAL: TypedContractMethod<[], [string], "view">;

  WITHDRAWAL_FEE_RATIO_LIMIT: TypedContractMethod<[], [bigint], "view">;

  amlPermitter: TypedContractMethod<[], [string], "view">;

  cancelDeposit: TypedContractMethod<
    [depositId: BigNumberish, deposit: DepositLib.DepositStruct],
    [void],
    "nonpayable"
  >;

  claimWithdrawals: TypedContractMethod<
    [withdrawals: WithdrawalLib.WithdrawalStruct[]],
    [void],
    "nonpayable"
  >;

  claimableWithdrawals: TypedContractMethod<
    [arg0: BytesLike],
    [bigint],
    "view"
  >;

  collectedWithdrawalFees: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  deploymentTime: TypedContractMethod<[], [bigint], "view">;

  depositERC1155: TypedContractMethod<
    [
      tokenAddress: AddressLike,
      recipientSaltHash: BytesLike,
      tokenId: BigNumberish,
      amount: BigNumberish,
      amlPermission: BytesLike,
      eligibilityPermission: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  depositERC20: TypedContractMethod<
    [
      tokenAddress: AddressLike,
      recipientSaltHash: BytesLike,
      amount: BigNumberish,
      amlPermission: BytesLike,
      eligibilityPermission: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  depositERC721: TypedContractMethod<
    [
      tokenAddress: AddressLike,
      recipientSaltHash: BytesLike,
      tokenId: BigNumberish,
      amlPermission: BytesLike,
      eligibilityPermission: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  depositNativeToken: TypedContractMethod<
    [
      recipientSaltHash: BytesLike,
      amlPermission: BytesLike,
      eligibilityPermission: BytesLike
    ],
    [void],
    "payable"
  >;

  eligibilityPermitter: TypedContractMethod<[], [string], "view">;

  getDepositData: TypedContractMethod<
    [depositId: BigNumberish],
    [DepositQueueLib.DepositDataStructOutput],
    "view"
  >;

  getDepositDataBatch: TypedContractMethod<
    [depositIds: BigNumberish[]],
    [DepositQueueLib.DepositDataStructOutput[]],
    "view"
  >;

  getDepositDataHash: TypedContractMethod<
    [depositId: BigNumberish],
    [string],
    "view"
  >;

  getLastDepositId: TypedContractMethod<[], [bigint], "view">;

  getLastRelayedDepositId: TypedContractMethod<[], [bigint], "view">;

  getNativeTokenIndex: TypedContractMethod<[], [bigint], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getTokenIndex: TypedContractMethod<
    [tokenType: BigNumberish, tokenAddress: AddressLike, tokenId: BigNumberish],
    [[boolean, bigint]],
    "view"
  >;

  getTokenInfo: TypedContractMethod<
    [tokenIndex: BigNumberish],
    [ITokenData.TokenInfoStructOutput],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _admin: AddressLike,
      _l1ScrollMessenger: AddressLike,
      _rollup: AddressLike,
      _withdrawal: AddressLike,
      _claim: AddressLike,
      _relayer: AddressLike,
      _contribution: AddressLike,
      initialERC20Tokens: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;

  isDepositValid: TypedContractMethod<
    [
      depositId: BigNumberish,
      recipientSaltHash: BytesLike,
      tokenIndex: BigNumberish,
      amount: BigNumberish,
      isEligible: boolean,
      sender: AddressLike
    ],
    [boolean],
    "view"
  >;

  onERC1155Received: TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "view"
  >;

  pauseDeposits: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  processWithdrawals: TypedContractMethod<
    [
      withdrawals: WithdrawalLib.WithdrawalStruct[],
      withdrawalHashes: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  relayDeposits: TypedContractMethod<
    [upToDepositId: BigNumberish, gasLimit: BigNumberish],
    [void],
    "payable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setPermitter: TypedContractMethod<
    [_amlPermitter: AddressLike, _eligibilityPermitter: AddressLike],
    [void],
    "nonpayable"
  >;

  setWithdrawalFeeRatio: TypedContractMethod<
    [tokenIndex: BigNumberish, feeRatio: BigNumberish],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unpauseDeposits: TypedContractMethod<[], [void], "nonpayable">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  withdrawCollectedFees: TypedContractMethod<
    [recipient: AddressLike, tokenIndices: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  withdrawalFeeRatio: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RELAYER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WITHDRAWAL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WITHDRAWAL_FEE_RATIO_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "amlPermitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelDeposit"
  ): TypedContractMethod<
    [depositId: BigNumberish, deposit: DepositLib.DepositStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimWithdrawals"
  ): TypedContractMethod<
    [withdrawals: WithdrawalLib.WithdrawalStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimableWithdrawals"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "collectedWithdrawalFees"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "deploymentTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositERC1155"
  ): TypedContractMethod<
    [
      tokenAddress: AddressLike,
      recipientSaltHash: BytesLike,
      tokenId: BigNumberish,
      amount: BigNumberish,
      amlPermission: BytesLike,
      eligibilityPermission: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositERC20"
  ): TypedContractMethod<
    [
      tokenAddress: AddressLike,
      recipientSaltHash: BytesLike,
      amount: BigNumberish,
      amlPermission: BytesLike,
      eligibilityPermission: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositERC721"
  ): TypedContractMethod<
    [
      tokenAddress: AddressLike,
      recipientSaltHash: BytesLike,
      tokenId: BigNumberish,
      amlPermission: BytesLike,
      eligibilityPermission: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositNativeToken"
  ): TypedContractMethod<
    [
      recipientSaltHash: BytesLike,
      amlPermission: BytesLike,
      eligibilityPermission: BytesLike
    ],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "eligibilityPermitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getDepositData"
  ): TypedContractMethod<
    [depositId: BigNumberish],
    [DepositQueueLib.DepositDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDepositDataBatch"
  ): TypedContractMethod<
    [depositIds: BigNumberish[]],
    [DepositQueueLib.DepositDataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDepositDataHash"
  ): TypedContractMethod<[depositId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getLastDepositId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLastRelayedDepositId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNativeTokenIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getTokenIndex"
  ): TypedContractMethod<
    [tokenType: BigNumberish, tokenAddress: AddressLike, tokenId: BigNumberish],
    [[boolean, bigint]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTokenInfo"
  ): TypedContractMethod<
    [tokenIndex: BigNumberish],
    [ITokenData.TokenInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _admin: AddressLike,
      _l1ScrollMessenger: AddressLike,
      _rollup: AddressLike,
      _withdrawal: AddressLike,
      _claim: AddressLike,
      _relayer: AddressLike,
      _contribution: AddressLike,
      initialERC20Tokens: AddressLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isDepositValid"
  ): TypedContractMethod<
    [
      depositId: BigNumberish,
      recipientSaltHash: BytesLike,
      tokenIndex: BigNumberish,
      amount: BigNumberish,
      isEligible: boolean,
      sender: AddressLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "onERC1155Received"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      arg1: AddressLike,
      arg2: BigNumberish,
      arg3: BigNumberish,
      arg4: BytesLike
    ],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "pauseDeposits"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "processWithdrawals"
  ): TypedContractMethod<
    [
      withdrawals: WithdrawalLib.WithdrawalStruct[],
      withdrawalHashes: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "relayDeposits"
  ): TypedContractMethod<
    [upToDepositId: BigNumberish, gasLimit: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPermitter"
  ): TypedContractMethod<
    [_amlPermitter: AddressLike, _eligibilityPermitter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setWithdrawalFeeRatio"
  ): TypedContractMethod<
    [tokenIndex: BigNumberish, feeRatio: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unpauseDeposits"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdrawCollectedFees"
  ): TypedContractMethod<
    [recipient: AddressLike, tokenIndices: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawalFeeRatio"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEvent(
    key: "ClaimedWithdrawal"
  ): TypedContractEvent<
    ClaimedWithdrawalEvent.InputTuple,
    ClaimedWithdrawalEvent.OutputTuple,
    ClaimedWithdrawalEvent.OutputObject
  >;
  getEvent(
    key: "DepositCanceled"
  ): TypedContractEvent<
    DepositCanceledEvent.InputTuple,
    DepositCanceledEvent.OutputTuple,
    DepositCanceledEvent.OutputObject
  >;
  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "DepositsRelayed"
  ): TypedContractEvent<
    DepositsRelayedEvent.InputTuple,
    DepositsRelayedEvent.OutputTuple,
    DepositsRelayedEvent.OutputObject
  >;
  getEvent(
    key: "DirectWithdrawalFailed"
  ): TypedContractEvent<
    DirectWithdrawalFailedEvent.InputTuple,
    DirectWithdrawalFailedEvent.OutputTuple,
    DirectWithdrawalFailedEvent.OutputObject
  >;
  getEvent(
    key: "DirectWithdrawalSuccessed"
  ): TypedContractEvent<
    DirectWithdrawalSuccessedEvent.InputTuple,
    DirectWithdrawalSuccessedEvent.OutputTuple,
    DirectWithdrawalSuccessedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PermitterSet"
  ): TypedContractEvent<
    PermitterSetEvent.InputTuple,
    PermitterSetEvent.OutputTuple,
    PermitterSetEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalClaimable"
  ): TypedContractEvent<
    WithdrawalClaimableEvent.InputTuple,
    WithdrawalClaimableEvent.OutputTuple,
    WithdrawalClaimableEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalFeeCollected"
  ): TypedContractEvent<
    WithdrawalFeeCollectedEvent.InputTuple,
    WithdrawalFeeCollectedEvent.OutputTuple,
    WithdrawalFeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalFeeRatioSet"
  ): TypedContractEvent<
    WithdrawalFeeRatioSetEvent.InputTuple,
    WithdrawalFeeRatioSetEvent.OutputTuple,
    WithdrawalFeeRatioSetEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawalFeeWithdrawn"
  ): TypedContractEvent<
    WithdrawalFeeWithdrawnEvent.InputTuple,
    WithdrawalFeeWithdrawnEvent.OutputTuple,
    WithdrawalFeeWithdrawnEvent.OutputObject
  >;

  filters: {
    "ClaimedWithdrawal(address,bytes32)": TypedContractEvent<
      ClaimedWithdrawalEvent.InputTuple,
      ClaimedWithdrawalEvent.OutputTuple,
      ClaimedWithdrawalEvent.OutputObject
    >;
    ClaimedWithdrawal: TypedContractEvent<
      ClaimedWithdrawalEvent.InputTuple,
      ClaimedWithdrawalEvent.OutputTuple,
      ClaimedWithdrawalEvent.OutputObject
    >;

    "DepositCanceled(uint256)": TypedContractEvent<
      DepositCanceledEvent.InputTuple,
      DepositCanceledEvent.OutputTuple,
      DepositCanceledEvent.OutputObject
    >;
    DepositCanceled: TypedContractEvent<
      DepositCanceledEvent.InputTuple,
      DepositCanceledEvent.OutputTuple,
      DepositCanceledEvent.OutputObject
    >;

    "Deposited(uint256,address,bytes32,uint32,uint256,bool,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "DepositsRelayed(uint256,uint256,bytes)": TypedContractEvent<
      DepositsRelayedEvent.InputTuple,
      DepositsRelayedEvent.OutputTuple,
      DepositsRelayedEvent.OutputObject
    >;
    DepositsRelayed: TypedContractEvent<
      DepositsRelayedEvent.InputTuple,
      DepositsRelayedEvent.OutputTuple,
      DepositsRelayedEvent.OutputObject
    >;

    "DirectWithdrawalFailed(bytes32,tuple)": TypedContractEvent<
      DirectWithdrawalFailedEvent.InputTuple,
      DirectWithdrawalFailedEvent.OutputTuple,
      DirectWithdrawalFailedEvent.OutputObject
    >;
    DirectWithdrawalFailed: TypedContractEvent<
      DirectWithdrawalFailedEvent.InputTuple,
      DirectWithdrawalFailedEvent.OutputTuple,
      DirectWithdrawalFailedEvent.OutputObject
    >;

    "DirectWithdrawalSuccessed(bytes32,address)": TypedContractEvent<
      DirectWithdrawalSuccessedEvent.InputTuple,
      DirectWithdrawalSuccessedEvent.OutputTuple,
      DirectWithdrawalSuccessedEvent.OutputObject
    >;
    DirectWithdrawalSuccessed: TypedContractEvent<
      DirectWithdrawalSuccessedEvent.InputTuple,
      DirectWithdrawalSuccessedEvent.OutputTuple,
      DirectWithdrawalSuccessedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PermitterSet(address,address)": TypedContractEvent<
      PermitterSetEvent.InputTuple,
      PermitterSetEvent.OutputTuple,
      PermitterSetEvent.OutputObject
    >;
    PermitterSet: TypedContractEvent<
      PermitterSetEvent.InputTuple,
      PermitterSetEvent.OutputTuple,
      PermitterSetEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "WithdrawalClaimable(bytes32)": TypedContractEvent<
      WithdrawalClaimableEvent.InputTuple,
      WithdrawalClaimableEvent.OutputTuple,
      WithdrawalClaimableEvent.OutputObject
    >;
    WithdrawalClaimable: TypedContractEvent<
      WithdrawalClaimableEvent.InputTuple,
      WithdrawalClaimableEvent.OutputTuple,
      WithdrawalClaimableEvent.OutputObject
    >;

    "WithdrawalFeeCollected(uint32,uint256)": TypedContractEvent<
      WithdrawalFeeCollectedEvent.InputTuple,
      WithdrawalFeeCollectedEvent.OutputTuple,
      WithdrawalFeeCollectedEvent.OutputObject
    >;
    WithdrawalFeeCollected: TypedContractEvent<
      WithdrawalFeeCollectedEvent.InputTuple,
      WithdrawalFeeCollectedEvent.OutputTuple,
      WithdrawalFeeCollectedEvent.OutputObject
    >;

    "WithdrawalFeeRatioSet(uint32,uint256)": TypedContractEvent<
      WithdrawalFeeRatioSetEvent.InputTuple,
      WithdrawalFeeRatioSetEvent.OutputTuple,
      WithdrawalFeeRatioSetEvent.OutputObject
    >;
    WithdrawalFeeRatioSet: TypedContractEvent<
      WithdrawalFeeRatioSetEvent.InputTuple,
      WithdrawalFeeRatioSetEvent.OutputTuple,
      WithdrawalFeeRatioSetEvent.OutputObject
    >;

    "WithdrawalFeeWithdrawn(address,uint32,uint256)": TypedContractEvent<
      WithdrawalFeeWithdrawnEvent.InputTuple,
      WithdrawalFeeWithdrawnEvent.OutputTuple,
      WithdrawalFeeWithdrawnEvent.OutputObject
    >;
    WithdrawalFeeWithdrawn: TypedContractEvent<
      WithdrawalFeeWithdrawnEvent.InputTuple,
      WithdrawalFeeWithdrawnEvent.OutputTuple,
      WithdrawalFeeWithdrawnEvent.OutputObject
    >;
  };
}
