/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockL2ScrollMessangerSol from "./MockL2ScrollMessanger.sol";
export type { mockL2ScrollMessangerSol };
